echo Install OpenSSH Server...
%SystemDrive%\Windows\Setup\Scripts\OpenSSH-Server-x64.msi /quiet /norestart /log %windir%\Temp\OpenSSH-Server-x64.log

echo Update OpenSSH Server Firewall Rules...
powershell.exe -Command "Remove-NetFirewallRule -DisplayName 'OpenSSH SSH Server Preview (sshd)'; New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -Profile Any; Start-Service sshd; Set-Service -Name sshd -StartupType Automatic"